#端口
server:
  port: 9001
  servlet:
    context-path: /patrolapi/

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/activiti7?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: postgres
    password: postgres
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 10
      filter:
        commons-log:
          connection-logger-name: stat,wall,log4j
        stat:
          log-slow-sql: true
          slow-sql-millis: 4000
          merge-sql: false
      use-global-data-source-stat: true
  activiti:
    # activiti 配置
    # 1 数据库更新策略
    #   1.1 false：       默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。（生产环境常用）
    #   1.2 true：        activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。（开发时常用）
    #   1.3 create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。（单元测试常用）
    #   1.4 drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）。
    database-schema-update: drop-create
    # 自动部署验证设置:true-开启（默认）、false-关闭【如果不关闭，那么部署到不同的服务器上，processes下的bpmn文件会被重新部署！】
    check-process-definitions: true
    # 这个属性是激活作业执行器，它的默认参数是false，只有设为true，activiti启动的时候才会开启线程池去扫描定时操作的任务
    asyncExecutorActivate: false
    #流程定义文件存放目录,要具体到某个目录
#    process-definition-location-prefix: classpath:/processes/
#    database-schema: ACTIVITI
    history-level: full
    db-history-used: true

mybatis:
  type-aliases-package: com.swust.activiti7.dao
  mapper-locations: classpath*:mapper/**/*.xml